#!/bin/sh

# Usage: make_password [-v num=n] [-v len=n] [-v debug=1]
#
# Number of Passwords
# Use "-v num=n" on the command line to specify the number 
# of passwords.
# (n must be >= 1; the default is 1)
# 
# Password Length
# Use "-v len=n" on the command line to specify the length 
# of the passwords.
# (n must be >= 8 and <= 16; the default is 8)
# 
# Debug Output
# Use "-v debug=1" on the command line to enable debug 
# messages.
# The debug messages report parameter errors and also the 
# number of passwords, password length, and number of 
# characters from each group of characters.

awk -f make_password.awk $*
